### ISSUE TITLE
broken packages dockerfile for Debian Stretch

### ISSUE THREAD

**Issue by nvjacobo** [anadahz/ooni-sync-docker#1]
docker build -t ooni-sync:docker .
Sending build context to Docker daemon  110.6kB
Step 1/8 : FROM rocker/r-base
latest: Pulling from rocker/r-base
71c170c5dae2: Pull complete 
1b76173b98c5: Pull complete 
1b00be862536: Pull complete 
c48ed365264c: Pull complete 
b2f3e26a95d6: Pull complete 
bdb9fc7fc7fb: Pull complete 
Digest: sha256:0589141389482d3211dbc9ccef20e1b426cc8ed7644c2ef0f60862becf3bea4e
Status: Downloaded newer image for rocker/r-base:latest
 ---> 9b7fc6df9690
Step 2/8 : ENV DATA_PATH /data
 ---> Running in 4aef4d46e99b
Removing intermediate container 4aef4d46e99b
 ---> 9125e8daa629
Step 3/8 : RUN apt-get update -qq &&     apt-get install -yqq xz-utils jq r-cran-ggplot2 r-cran-data.table curl
 ---> Running in 8eb2e86f8881
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update -qq &&     apt-get install -yqq xz-utils jq r-cran-ggplot2 r-cran-data.table curl' returned a non-zero code: 100

**Comment by anadahz** [comment]
9239b3a should fix this issue.
Thank you for checking out this repo.

**Comment by nvjacobo** [comment]
It works
